package com.acme.rfq;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ProductID")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label("ProductName")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("ProductPrice")
	private java.lang.Double price;

	@org.kie.api.definition.type.Label(value = "ProductDescription")
	private java.lang.String description;

	public Product() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public Product(java.lang.Integer id, java.lang.String name,
			java.lang.Double price, java.lang.String description) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.description = description;
	}

}